import 'package:auvnet_store/core/service/networking/api_constants.dart';
import 'package:auvnet_store/features/auth/data/models/login_request_body.dart';
import 'package:auvnet_store/features/auth/data/models/login_response.dart';
import 'package:auvnet_store/features/auth/data/models/sign_up_request_body.dart';
import 'package:auvnet_store/features/auth/data/models/signup_response.dart';
import 'package:auvnet_store/features/home/data/models/products_response.dart';
import 'package:auvnet_store/features/home/data/models/categories_response.dart';
import 'package:auvnet_store/features/product_details/data/models/product_response.dart';
import 'package:auvnet_store/features/profile/data/models/profile_responce.dart';
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

part 'api_service.g.dart'; // This file is generated by Retrofit to handle API requests.

@RestApi(baseUrl: Apiconstants.baseUrl) // Base URL for the API service
abstract class ApiService {
  // Factory constructor for ApiService, which uses Dio for HTTP requests
  factory ApiService(Dio dio, {String baseUrl}) = _ApiService;

  // Endpoint for user login
  @POST(Apiconstants.login)
  Future<LoginResponse> login(
    @Body() LoginRequestBody body, // Request body for login
  );

  // Endpoint for user registration
  @POST(Apiconstants.signup)
  Future<SignupResponse> signUp(
    @Body() SignupRequestBody body, // Request body for signup
  );

  // Endpoint to get the user's profile information
  @GET(Apiconstants.profile)
  Future<ProfileResponse> profile();

  // Endpoint to get a list of products (banners)
  @GET(Apiconstants.banners)
  Future<List<ProductResponse>> products();

  // Endpoint to get a list of categories
  @GET(Apiconstants.category)
  Future<List<CategoryResponse>> categories();

  // Endpoint to get details of a specific product by ID
  @GET("${Apiconstants.product}{id}")
  Future<ProductDetailsResponse> productDetails(@Path("id") int productId);
}
